added sorting by attributes and filtering in search query
ivario123/D0018E-e-comerce pull request #32
Opened 2023-02-16 22:23 UTC by Kyrne

This PR adds the ability to sort by attributes such as name or price, and filtering by category after searching for a product.

## Added

This PR adds 
`templates/search.html`
This template is used for search results.

## Modified

 - `src/search.py`, restructured search by making splitting it up into more functions. Also added the ability to sort by price and name, both ascending and descending.
 - `static/js/search.js`, added a get method for sorting
- `templates/jinja_macros/product_listing.html`, added drop down menu as a macro
- Also added the drop down menu in `templates/index.html` and `templates/search.html`

## Testing

This can be tested by searching and sorting with different combinations, both before making a search and after making a search.
 
closes #28 
closes #27

2023-02-18 18:45 UTC, Marmak95 approved these changes
Everything is working when it comes to sorting by attributes and filtering in search query.
I didn't find any issues with the code.

2023-02-20 07:45 UTC, ivario123 requested changes
I think that it looks good in general, with just a few pointers. I have not tested it yet though.

2023-02-20 07:45 UTC, ivario123 commented on templates/jinja_macros/navbar.html
> +        <!--TODO keep last search after search in search bar-->
I think we should remove this comment and make a new issue for that UI fix instead.

2023-02-20 07:45 UTC, ivario123 commented on templates/jinja_macros/product_listing.html
> +<script>
We should avoid inline scripts, move this to a separate file

2023-02-20 07:45 UTC, ivario123 commented on templates/search.html
> +<!--TODO save selected filters -->
Ditto

2023-02-20 07:45 UTC, ivario123 commented on templates/search.html
> +<script>
Ditto

2023-02-20 07:45 UTC, ivario123 commented on src/sql/inventory/getters.py
> +    super = cursor.fetchall()
Add

```python
if not super:
   raise Exception("No such super category")
```
This will roll back the transaction.

2023-02-20 07:45 UTC, ivario123 commented on src/sql/inventory/getters.py
> +    super = cursor.fetchall()
Or just return an empty list since the transaction is non mutating.

2023-02-20 09:48 UTC, ivario123 commented
# Category filters are not visually persistent

When searching for a string of text, and then filtering on products there is no way to know what category filters are used since they are not highlighted in the list of categories. This could likely be resolved quite easily, look at how I did it in the index.

2023-02-20 09:50 UTC, ivario123 commented
# Categories not applied to text

When first filtering on categories and then filtering on text the categories are not applied.

2023-02-20 09:52 UTC, ivario123 commented on templates/jinja_macros/product_listing.html
> +            <span>Sort after</span>
sort by

2023-02-20 09:55 UTC, ivario123 commented
First filtering on products removes the option to sort by ..filter..

2023-02-20 15:42 UTC, ivario123 approved these changes

2023-02-20 15:44 UTC, merged